import {
  DashboardSquare02Icon,
  FileSyncIcon,
  TaskDaily01Icon,
  Book02Icon,
  ArrowRightDoubleIcon,
  Wallet01Icon,
  CashbackPoundIcon,
  TransactionIcon,
  TaxesIcon,
  GitPullRequestIcon,
  DocumentValidationIcon,
  ProfileIcon,
  InstallingUpdates02Icon,
  NotificationIcon,
  InvoiceIcon,
  Message01Icon,
  Building01Icon,
  CreditCardIcon,
  UserCheck01Icon,
  GiftIcon,
  Unlink03Icon,
} from "@hugeicons/core-free-icons";

export type MenuSection = "primary" | "workspaces" | "operations" | "settings";

export interface MenuItem {
  slug: string;
  icon: any;
  label: string;
  href: string;
  children?: MenuItem[];
  section?: MenuSection;
  description?: string;
  isActive?: boolean;
  disabled?: boolean;
  count?: number;
  totalCount?: number;
}

export const menuData: MenuItem[] = [
  {
    slug: "dashboard",
    icon: DashboardSquare02Icon,
    label: "Dashboard",
    href: "/dashboard",
    children: [],
    section: "primary",
    description: "Company overview & status",
  },
  {
    slug: "company",
    icon: Building01Icon,
    label: "Company",
    href: "/dashboard/company",
    children: [],
    section: "primary",
    description: "Company overview & status",
  },
  // {
  //     slug: "global-library",
  //     icon: Book02Icon,
  //     label: "Global Library",
  //     href: "/dashboard/global-library",
  //     children: [],
  //     section: "primary",
  //     description: "Centralized document vault",
  // },
  // {
  //     slug: "documents",
  //     icon: DocumentValidationIcon,
  //     label: "Documents",
  //     href: "/dashboard/documents",
  //     children: [],
  //     section: "primary",
  //     description: "Store and access documents",
  // },

  {
    slug: "services-root",
    icon: GitPullRequestIcon,
    label: "Services",
    href: "/dashboard/services",
    section: "primary",
    description: "Accounting, audit & corporate services",
    children: [
      {
        slug: "accounting-bookkeeping",
        icon: Book02Icon,
        label: "Accounting & Bookkeeping",
        href: "/dashboard/services/bookkeeping",
        isActive: true,
        children: [
          {
            slug: "ab-docs",
            icon: DocumentValidationIcon,
            label: "Document Requests",
            href: "/dashboard/services/bookkeeping?tab=document_requests",
            count: 5,
            totalCount: 5,
          },
          {
            slug: "ab-lib",
            icon: Book02Icon,
            label: "Library",
            href: "/dashboard/services/bookkeeping?tab=library",
          },
          {
            slug: "ab-compliance",
            icon: TaxesIcon,
            label: "Compliance Calendar",
            href: "/dashboard/services/bookkeeping?tab=compliance_calendar",
          },
          {
            slug: "ab-history",
            icon: TaskDaily01Icon,
            label: "Service History",
            href: "/dashboard/services/bookkeeping?tab=service_history",
          },
          {
            slug: "ab-messages",
            icon: Message01Icon,
            label: "Messages",
            href: "/dashboard/services/bookkeeping?tab=messages",
            count: 8,
            totalCount: 10,
          },
          {
            slug: "ab-mbr-filings",
            icon: TaskDaily01Icon,
            label: "Filings",
            href: "/dashboard/services/bookkeeping?tab=mbr_filings",
          },
          {
            slug: "invoices",
            icon: InvoiceIcon,
            label: "Invoices",
            href: "/dashboard/invoices",
            isActive: true,
          },
          {
            slug: "bank-transactions",
            icon: TransactionIcon,
            label: "Bank Transactions",
            href: "/dashboard/bank-transactions",
            isActive: true,
          },
          {
            slug: "cash",
            icon: Wallet01Icon,
            label: "Cash",
            href: "/dashboard/cash",
            isActive: true,
          },
          {
            slug: "change-in-bank",
            icon: TransactionIcon,
            label: "Change in Bank Balances",
            href: "/dashboard/change-in-bank-balances",
            isActive: true,
          },
          {
            slug: "general-ledger",
            icon: Book02Icon,
            label: "General Ledger",
            href: "/dashboard/general-ledger",
            isActive: true,
          },
          {
            slug: "ap-ar-aging",
            icon: TransactionIcon,
            label: "AP/AR Aging",
            href: "#",
            isActive: true,
            children: [
              {
                slug: "ap-aging",
                label: "Accounts Payable",
                href: "/dashboard/ap-ar-aging/account-payble-aging",
                icon: TransactionIcon,
              },
              {
                slug: "ar-aging",
                label: "Accounts Receivable",
                href: "/dashboard/ap-ar-aging/account-receivable-aging",
                icon: TransactionIcon,
              },
            ],
          },
          {
            slug: "financial-statements",
            icon: DocumentValidationIcon,
            label: "Financial Statements",
            href: "#",
            isActive: true,
            children: [
              {
                slug: "balance-sheet",
                label: "Balance Sheet",
                href: "/dashboard/financial-statements/balance-sheet",
                icon: DocumentValidationIcon,
              },
              {
                slug: "profit-loss",
                label: "Profit & Loss",
                href: "/dashboard/financial-statements/profit-loss",
                icon: DocumentValidationIcon,
              },
              {
                slug: "cash-flow",
                label: "Cash Flow",
                href: "/dashboard/financial-statements/cash-flow-statement",
                icon: DocumentValidationIcon,
              },
            ],
          },
          {
            slug: "insights",
            icon: DashboardSquare02Icon,
            label: "Insights",
            href: "/dashboard/insights",
            isActive: true,
          },
        ],
      },
      {
        slug: "audit",
        icon: DocumentValidationIcon,
        label: "Audit",
        href: "/dashboard/services/audit",
        isActive: true,
        children: [
          {
            slug: "audit-docs",
            icon: DocumentValidationIcon,
            label: "Document Requests",
            href: "/dashboard/services/audit?tab=document_requests",
            count: 5,
            totalCount: 12,
          },
          {
            slug: "audit-lib",
            icon: Book02Icon,
            label: "Library",
            href: "/dashboard/services/audit?tab=library",
          },
          {
            slug: "audit-compliance",
            icon: TaxesIcon,
            label: "Compliance Calendar",
            href: "/dashboard/services/audit?tab=compliance_calendar",
          },
          {
            slug: "audit-history",
            icon: TaskDaily01Icon,
            label: "Service History",
            href: "/dashboard/services/audit?tab=service_history",
          },
          {
            slug: "audit-messages",
            icon: Message01Icon,
            label: "Messages",
            href: "/dashboard/services/audit?tab=messages",
            count: 1,
            totalCount: 4,
          },
          {
            slug: "audit-mbr-filings",
            icon: TaskDaily01Icon,
            label: "Filings",
            href: "/dashboard/services/audit?tab=mbr_filings",
          },
          {
            slug: "engagements",
            icon: CashbackPoundIcon,
            label: "Engagements",
            href: "/dashboard/engagements",
            isActive: true,
          },
        ],
      },
      {
        slug: "vat",
        icon: TaxesIcon,
        label: "VAT",
        href: "/dashboard/services/vat",
        isActive: true,
        children: [
          {
            slug: "vat-periods",
            icon: TaxesIcon,
            label: "VAT Periods",
            href: "/dashboard/services/vat?tab=vat_periods",
          },
          {
            slug: "vat-docs",
            icon: DocumentValidationIcon,
            label: "Document Requests",
            href: "/dashboard/services/vat?tab=document_requests",
          },
          {
            slug: "vat-lib",
            icon: Book02Icon,
            label: "Library",
            href: "/dashboard/services/vat?tab=library",
          },
          {
            slug: "vat-compliance",
            icon: TaxesIcon,
            label: "Compliance Calendar",
            href: "/dashboard/services/vat?tab=compliance_calendar",
          },
          {
            slug: "vat-history",
            icon: TaskDaily01Icon,
            label: "Service History",
            href: "/dashboard/services/vat?tab=service_history",
          },
          {
            slug: "vat-messages",
            icon: Message01Icon,
            label: "Messages",
            href: "/dashboard/services/vat?tab=messages",
          },
          {
            slug: "vat-mbr-filings",
            icon: TaskDaily01Icon,
            label: "Filings",
            href: "/dashboard/services/vat?tab=mbr_filings",
          },
          {
            slug: "vat-malta",
            icon: TaxesIcon,
            label: "VAT — Malta",
            href: "/dashboard/services/vat/malta",
            isActive: true,
          },
        ],
      },
      {
        slug: "tax",
        icon: TaxesIcon,
        label: "Tax",
        href: "/dashboard/services/tax",
        isActive: true,
        children: [
          {
            slug: "tax-docs",
            icon: DocumentValidationIcon,
            label: "Document Requests",
            href: "/dashboard/services/tax?tab=document_requests",
          },
          {
            slug: "tax-lib",
            icon: Book02Icon,
            label: "Library",
            href: "/dashboard/services/tax?tab=library",
          },
          {
            slug: "tax-compliance",
            icon: TaxesIcon,
            label: "Compliance Calendar",
            href: "/dashboard/services/tax?tab=compliance_calendar",
          },
          {
            slug: "tax-history",
            icon: TaskDaily01Icon,
            label: "Service History",
            href: "/dashboard/services/tax?tab=service_history",
          },
          {
            slug: "tax-messages",
            icon: Message01Icon,
            label: "Messages",
            href: "/dashboard/services/tax?tab=messages",
          },
          {
            slug: "tax-mbr-filings",
            icon: TaskDaily01Icon,
            label: "Filings",
            href: "/dashboard/services/tax?tab=mbr_filings",
          },
        ],
      },
      {
        slug: "csp",
        icon: Building01Icon,
        label: "Corporate Services (CSP)",
        href: "/dashboard/services/csp-mbr",
        isActive: true,
        children: [
          {
            slug: "csp-docs",
            icon: DocumentValidationIcon,
            label: "Document Requests",
            href: "/dashboard/services/csp-mbr?tab=document_requests",
          },
          {
            slug: "csp-lib",
            icon: Book02Icon,
            label: "Library",
            href: "/dashboard/services/csp-mbr?tab=library",
          },
          {
            slug: "csp-compliance",
            icon: TaxesIcon,
            label: "Compliance Calendar",
            href: "/dashboard/services/csp-mbr?tab=compliance_calendar",
          },
          {
            slug: "csp-history",
            icon: TaskDaily01Icon,
            label: "Service History",
            href: "/dashboard/services/csp-mbr?tab=service_history",
          },
          {
            slug: "csp-messages",
            icon: Message01Icon,
            label: "Messages",
            href: "/dashboard/services/csp-mbr?tab=messages",
          },
        ],
      },
      {
        slug: "payroll",
        icon: CashbackPoundIcon,
        label: "Payroll",
        href: "/dashboard/services/payroll",
        isActive: true,
        children: [
          {
            slug: "payroll-docs",
            icon: DocumentValidationIcon,
            label: "Document Requests",
            href: "/dashboard/services/payroll?tab=document_requests",
          },
          {
            slug: "payroll-lib",
            icon: Book02Icon,
            label: "Library",
            href: "/dashboard/services/payroll?tab=library",
          },
          {
            slug: "payroll-compliance",
            icon: TaxesIcon,
            label: "Compliance Calendar",
            href: "/dashboard/services/payroll?tab=compliance_calendar",
          },
          {
            slug: "payroll-history",
            icon: TaskDaily01Icon,
            label: "Service History",
            href: "/dashboard/services/payroll?tab=service_history",
          },
          {
            slug: "payroll-messages",
            icon: Message01Icon,
            label: "Messages",
            href: "/dashboard/services/payroll?tab=messages",
          },
          {
            slug: "payroll-mbr-filings",
            icon: TaskDaily01Icon,
            label: "Filings",
            href: "/dashboard/services/payroll?tab=mbr_filings",
          },
          {
            slug: "payroll(malta)",
            icon: CashbackPoundIcon,
            label: "Payroll (Malta)",
            href: "/dashboard/services/payroll/malta",
            isActive: true,
          },
        ],
      },

      {
        slug: "cfo",
        icon: Wallet01Icon,
        label: "CFO",
        href: "/dashboard/services/cfo",
        isActive: true,
        children: [
          {
            slug: "cfo-docs",
            icon: DocumentValidationIcon,
            label: "Document Requests",
            href: "/dashboard/services/cfo?tab=document_requests",
          },
          {
            slug: "cfo-milestones",
            icon: TaskDaily01Icon,
            label: "Milestones",
            href: "/dashboard/services/cfo?tab=milestones",
          },
          {
            slug: "cfo-lib",
            icon: Book02Icon,
            label: "Library",
            href: "/dashboard/services/cfo?tab=library",
          },
          {
            slug: "cfo-compliance",
            icon: TaxesIcon,
            label: "Compliance Calendar",
            href: "/dashboard/services/cfo?tab=compliance_calendar",
          },
          {
            slug: "cfo-messages",
            icon: Message01Icon,
            label: "Messages",
            href: "/dashboard/services/cfo?tab=messages",
          },
        ],
      },
      {
        slug: "mbr-filing",
        icon: DocumentValidationIcon,
        label: "MBR Filings",
        href: "/dashboard/services/mbr-filing",
        isActive: true,
        children: [
          {
            slug: "mbr-overview",
            icon: DocumentValidationIcon,
            label: "Overview",
            href: "/dashboard/services/mbr-filing?tab=overview",
          },
          {
            slug: "mbr-filings",
            icon: TaskDaily01Icon,
            label: "Filings",
            href: "/dashboard/services/mbr-filing?tab=filings",
          },
        ],
      },
      {
        slug: "incorporation",
        icon: GitPullRequestIcon,
        label: "Incorporation",
        href: "/dashboard/services/incorporation",
        isActive: true,
        children: [
          {
            slug: "inc-docs",
            icon: DocumentValidationIcon,
            label: "Document Requests",
            href: "/dashboard/services/incorporation?tab=document_requests",
          },
          {
            slug: "inc-milestones",
            icon: TaskDaily01Icon,
            label: "Milestones",
            href: "/dashboard/services/incorporation?tab=milestones",
          },
          {
            slug: "inc-lib",
            icon: Book02Icon,
            label: "Library",
            href: "/dashboard/services/incorporation?tab=library",
          },
          {
            slug: "inc-compliance",
            icon: TaxesIcon,
            label: "Compliance Calendar",
            href: "/dashboard/services/incorporation?tab=compliance_calendar",
          },
          {
            slug: "inc-messages",
            icon: Message01Icon,
            label: "Messages",
            href: "/dashboard/services/incorporation?tab=messages",
          },
        ],
      },
      {
        slug: "business-plans",
        icon: DocumentValidationIcon,
        label: "Business Plans",
        href: "/dashboard/services/business-plans",
        isActive: true,
        children: [
          {
            slug: "bp-docs",
            icon: DocumentValidationIcon,
            label: "Document Requests",
            href: "/dashboard/services/business-plans?tab=document_requests",
          },
          {
            slug: "bp-milestones",
            icon: TaskDaily01Icon,
            label: "Milestones",
            href: "/dashboard/services/business-plans?tab=milestones",
          },
          {
            slug: "bp-lib",
            icon: Book02Icon,
            label: "Library",
            href: "/dashboard/services/business-plans?tab=library",
          },
          {
            slug: "bp-compliance",
            icon: TaxesIcon,
            label: "Compliance Calendar",
            href: "/dashboard/services/business-plans?tab=compliance_calendar",
          },
          {
            slug: "bp-messages",
            icon: Message01Icon,
            label: "Messages",
            href: "/dashboard/services/business-plans?tab=messages",
          },
        ],
      },
      {
        slug: "liquidation",
        icon: Unlink03Icon,
        label: "Liquidation",
        href: "/dashboard/services/liquidation",
        isActive: true,
        children: [
          {
            slug: "liq-docs",
            icon: DocumentValidationIcon,
            label: "Document Requests",
            href: "/dashboard/services/liquidation?tab=document_requests",
          },
          {
            slug: "liq-milestones",
            icon: TaskDaily01Icon,
            label: "Milestones",
            href: "/dashboard/services/liquidation?tab=milestones",
          },
          {
            slug: "liq-lib",
            icon: Book02Icon,
            label: "Library",
            href: "/dashboard/services/liquidation?tab=library",
          },
          {
            slug: "liq-compliance",
            icon: TaxesIcon,
            label: "Compliance Calendar",
            href: "/dashboard/services/liquidation?tab=compliance_calendar",
          },
          {
            slug: "liq-messages",
            icon: Message01Icon,
            label: "Messages",
            href: "/dashboard/services/liquidation?tab=messages",
          },
        ],
      },
      {
        slug: "banking-payments",
        icon: CreditCardIcon,
        label: "Banking & Payments",
        href: "/dashboard/services/banking-payments",
        disabled: true,
      },
      {
        slug: "regulated-licences",
        icon: ProfileIcon,
        label: "Regulated Licences",
        href: "/dashboard/services/regulated-licences",
        disabled: true,
      },
      {
        slug: "residency-mobility",
        icon: UserCheck01Icon,
        label: "Residency & Mobility",
        href: "/dashboard/services/residency-mobility",
        disabled: true,
      },
      {
        slug: "grants-incentives",
        icon: GiftIcon,
        label: "Grants & Incentives",
        href: "/dashboard/services/grants-incentives",
        isActive: true,
      },
      {
        slug: "corporate-transactions",
        icon: TransactionIcon,
        label: "Corporate Transactions",
        href: "/dashboard/services/corporate-transactions",
        disabled: true,
      },
      // {
      //   slug: "library",
      //   icon: Book02Icon,
      //   label: "Library",
      //   href: "/dashboard/services#library",
      //   disabled: true,
      //   description: "Centralized document vault",
      // },
    ],
  },
  // {
  //     slug: "compliance-setup",
  //     icon: InstallingUpdates02Icon,
  //     label: "Compliance Setup",
  //     href: "/dashboard/compliance/setup",
  //     children: [],
  //     section: "primary",
  //     description: "Configure compliance anchors & active services",
  // },
  {
    slug: "compliance",
    icon: TaxesIcon,
    label: "Compliance Calendar",
    href: "/dashboard/compliance",
    children: [],
    section: "primary",
    description: "Statutory deadlines & filings",
  },
  {
    slug: "messages",
    icon: Message01Icon,
    label: "Messages",
    href: "/dashboard/messages",
    children: [],
    section: "primary",
    description: "Chat with your service team",
    count: 8,
    totalCount: 15,
  },
  {
    slug: "reseller-analytics",
    icon: TransactionIcon,
    label: "Reseller Analytics",
    href: "/dashboard/reseller-analytics",
    children: [],
    section: "primary",
    description: "Track signups and commission earnings",
  },
  {
    slug: "todo-list",
    icon: TaskDaily01Icon,
    label: "To-Do List",
    href: "/dashboard/todo-list",
    children: [],
    section: "operations",
    description: "Tasks requiring your action",
  },
  {
    slug: "notifications",
    icon: NotificationIcon,
    label: "Alerts & Notifications",
    href: "/dashboard/notifications",
    children: [],
    section: "operations",
    description: "Important updates & reminders",
  },
  // {
  //    slug: "document-organizer",
  //     icon: DocumentValidationIcon,
  //     label: "Document Organizer",
  //     href: "/dashboard/document-organizer/document-listing",
  //     description: "Auto-sort & organise files",
  //     children: [
  //         {
  //             slug: "upload",
  //             icon: ArrowRightDoubleIcon,
  //             label: "Upload Documents",
  //             href: "/dashboard/document-organizer/document-upload",
  //         },
  //         {
  //             slug: "listing",
  //             icon: ArrowRightDoubleIcon,
  //             label: "View Documents",
  //             href: "/dashboard/document-organizer/document-listing",
  //         },
  //     ],
  //     section: "operations",
  // },
  {
    slug: "quickbooks-sync",
    icon: FileSyncIcon,
    label: "Quickbooks Sync",
    href: "/dashboard/quickbooks-sync",
    description: "Accounting software connection",
    children: [],
    section: "operations",
  },
  {
    slug: "settings",
    icon: InstallingUpdates02Icon,
    label: "Settings",
    description: "Company & user preferences",
    href: "/dashboard/settings",
    section: "settings",
    children: [
      // {
      //     slug: "company-profile",
      //     icon: Building01Icon,
      //     label: "Company Profile",
      //     href: "/dashboard/settings/company-profile",
      // },
      // {
      //     slug: "users-permissions",
      //     icon: ProfileIcon,
      //     label: "Users & Permissions",
      //     href: "/dashboard/settings/users-permissions",
      // },
      // {
      //     slug: "preferences",
      //     icon: InstallingUpdates02Icon,
      //     label: "Preferences",
      //     href: "/dashboard/settings/preferences",
      // },
    ],
  },
];
